# Generated by Django 5.2.7 on 2025-10-18 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "device_owners",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["external_id", "is_active"],
                        name="device_owne_externa_ccc128_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_token",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        default="ios",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="notifications.deviceowner",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_token", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("badge", models.IntegerField(blank=True, null=True)),
                ("sound", models.CharField(default="default", max_length=50)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("thread_id", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(5, "Normal"), (10, "High")], default=5
                    ),
                ),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="APNs will discard notification after this time if not delivered",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("invalid_token", "Invalid Token"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apns_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notifications.device",
                    ),
                ),
            ],
            options={
                "db_table": "push_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_token", "is_active"], name="devices_device__d7ef83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["status", "scheduled_at"], name="push_notifi_status_ef492c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["device_token", "created_at"],
                name="push_notifi_device__e219d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["created_at"], name="push_notifi_created_d308cb_idx"
            ),
        ),
    ]
